### ISSUE TITLE
Remove extra social media links

### ISSUE THREAD

**Issue by cseas** [glugmvit/gwoc#4]
Remove Google Plus and Skype from the homepage
![Selection_005](https://user-images.githubusercontent.com/29686866/97032662-cd0ad080-157f-11eb-9e6f-1cb471d1692f.png)

**Comment by wandersonpsantos** [comment]
I will do this ,can u assign it to me?

**Comment by prakruthi3** [comment]
Fixed

**Comment by cseas** [comment]
Not fixed yet, I can still see the extra icons here:
https://gwoc.glugmvit.com/

**Comment by cseas** [comment]
Extra icons are gone now
